/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/airplane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.optimize_2.geometry} material={nodes.optimize_2.material} rotation={[Math.PI / 2, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/airplane.glb')
